### ISSUE TITLE
Overnight JavaScript Alert

### ISSUE THREAD

**Issue by leif81** [leif81/bzkanban#21]
When the board is left open overnight I regularly see this alert first thing in the morning:

![bzkanban-overnight-error](https://cloud.githubusercontent.com/assets/494426/10247157/0fa7ea1a-68e5-11e5-88e1-6ae8e96e8dd4.PNG)

I'm guessing it has something to do with the `scheduleCheckForUpdates` function that constantly polls the server. And maybe caused by when the db is being restored in the middle of the night?

**Comment by gizzmojr** [comment]
Definitely, since the scripts do a 'drop db' so if you manage to poll within the couple of minutes before the import is done I imagine you'd get an error like you show. 
This problem is only cause of the RO mirror, and once production gets upgraded and we point there instead it'll go away.

Could add some code so it doesn't just die, and instead goes into a longer sleep waiting.
Ex: wait 1 min, fail, wait longer, etc. Think when gmail loses connectivity.

**Comment by leif81** [comment]
Ya that's a good idea.

I think I'll also start sending our errors to the `console.log` too to make debugging easier because: 
- Copy/paste doesn't work from Javascript alerts. :frowning: 
- And the console can show a timestamp for free (must be toggled on in the settings) which would give us a better idea if this in fact lines up with when the db is being restored. Which I think we're confident it is though.

**Comment by leif81** [comment]
I think it's safe to close this one. Nothing else really to do.
