### ISSUE TITLE
Drop down single auto-selection

### ISSUE THREAD

**Issue by gizzmojr** [leif81/bzkanban#50]
Let's have it so if the dropdown list contains a single return (product & milestone), automatically select and move on. 

Example is a Product with a single milestone, it seems like wasted time waiting for the milestone list to display a single result.

**Comment by leif81** [comment]
Maybe eh...I've given it some thought before too, it's a simple enough change, but there's a couple reasons I resisted in the past. Bit of a rant follows, apologies. 🔈 

I'd prefer we encourage good use of milestones. I don't want to tell people how to use Bugzilla...but I will 😜 Bugs in the backlog should not be worked on. Bugzilla can even be configured to deny setting backlogged bugs to IN_PROGRESS, which is a really smart option. The main reason to not use that option is because... old habits die hard.

Now we could turn a blind eye to that argument, and instead just change the board behaviour so *all* products auto select the backlog milestone. But you'd probably agree that's not really desirable either because viewing the backlog is unlikely the action most users want to see when they have real milestones. Plus the extra load would slow the board down.

So ya, since this is an "agile" board I'd prefer we encourage agile behaviour. So for products that don't have anything but a backlog milestone, they should think about adding meaningful milestone names. For software products it's easy, versions or work packages are easy milestone names. But for non software products, I agree it can be harder to come up with good names. One idea I've seen is using milestone names like "FY2016". Everything that is planned to be worked on in the fiscal year goes in there, otherwise it's backlogged. A side benefit is that when FY2017 starts you can start it with a fresh board instead of seeing a whole lot of RESOLVED or VERIFIED bugs year after year clogging up the board.

Would that work?

**Comment by gizzmojr** [comment]
As someone who uses the board as an issue/tasking tracker, I hadn't considered breaking down by year or some other means. 
I will agree, that ask time goes on I would have to figure out to curb the growing resolved/verified list. 

Going to try that out, but I will also need to spoof up the back log feature, which I've already started on.

**Comment by gizzmojr** [comment]
Backlog viewing ability in 7168b0d251311689cb9bfd5c70f60a2fbd04d8e8, thoughts?

**Comment by leif81** [comment]
Sounds neat. I'm getting an error when running it though. When I press the "Show Backlog" button I get a js error.

Side note, since this is a new and experimental feature we should stick it on a branch at least for a while until the design and bugs are shaken out.

**Comment by gizzmojr** [comment]
Bah and I even mentioned putting it onto a branch too last time....arg! My bad.
If you have a moment, do a force push or I can if that's alright.

**Comment by leif81** [comment]
K, done. I've created a new branch named "backlog". Can you create a PR from that, add whatever fixes you want, and then when I have a sec to look it over I'll add some inline comments.

**Comment by gizzmojr** [comment]
Thanks, PR #51 opened.
:taco:
